### ISSUE TITLE
v221 immediately errors with "Error on loading security information from datafile:"

### ISSUE THREAD

**Issue by marcjw** [dkfurrow/moneydance-investment-reports#6]
I could use your expertise.  I started a thread on the InfiniteKind Support forums here:
https://infinitekind.tenderapp.com/discussions/moneydance-development/8035-extra-investment-reports-v221
But no one seems to know what to do with the error.  I'm wondering if you could please chime in?

<record>
<date>2023-12-06T22:50:38.844135587Z</date>
<millis>1701903038844</millis>
<nanos>135587</nanos>
<sequence>0</sequence>
<logger>com.moneydance.modules.features.invextension.LogController</logger>
<level>SEVERE</level>
<class>com.moneydance.modules.features.invextension.LogController</class>
<method>logException</method>
<thread>64</thread>
<message>Error on loading security information from datafile: </message>
<exception>
<message>java.lang.NullPointerException</message>
<frame>
<class>com.infinitekind.moneydance.model.Account</class>
<method><init></method>
<line>32</line>
</frame>
<frame>
<class>com.moneydance.modules.features.invextension.InvestmentAccountWrapper</class>
<method>createCashWrapper</method>
<line>136</line>
</frame>
<frame>
<class>com.moneydance.modules.features.invextension.InvestmentAccountWrapper</class>
<method><init></method>
<line>84</line>
</frame>
<frame>
<class>com.moneydance.modules.features.invextension.BulkSecInfo</class>
<method>getInvestmentAccountInfo</method>
<line>452</line>
</frame>
<frame>
<class>com.moneydance.modules.features.invextension.BulkSecInfo</class>
<method><init></method>
<line>139</line>
</frame>
<frame>
<class>com.moneydance.modules.features.invextension.MDData</class>
<method>generateCurrentInfo</method>
<line>79</line>
</frame>
<frame>
<class>com.moneydance.modules.features.invextension.ReportControlPanel$ReportExecutor</class>
<method>doInBackground</method>
<line>942</line>
</frame>
<frame>
<class>com.moneydance.modules.features.invextension.ReportControlPanel$ReportExecutor</class>
<method>doInBackground</method>
<line>914</line>
</frame>
<frame>
<class>javax.swing.SwingWorker$1</class>
<method>call</method>
</frame>
<frame>
<class>java.util.concurrent.FutureTask</class>
<method>run</method>
</frame>
<frame>
<class>javax.swing.SwingWorker</class>
<method>run</method>
</frame>
<frame>
<class>java.util.concurrent.ThreadPoolExecutor</class>
<method>runWorker</method>
</frame>
<frame>
<class>java.util.concurrent.ThreadPoolExecutor$Worker</class>
<method>run</method>
</frame>
<frame>
<class>java.lang.Thread</class>
<method>run</method>
</frame>
</exception>
</record>

**Comment by yogi1967** [comment]
Hi Dale. Quick question. Do your changes work both in latest MD build and also prior builds too?

Note: 5064 is out and this fixes a couple more NPEs
https://infinitekind.com/preview

**Comment by yogi1967** [comment]
Refer: https://infinitekind.tenderapp.com/discussions/moneydance-development/8035-extra-investment-reports-v221
